### ISSUE TITLE
Руслан, твоя файловая структура сосёт жопу, реально

### ISSUE THREAD

**Issue by arf1e** [polundra-digital/recirculators#3]
![изображение](https://user-images.githubusercontent.com/22895289/101267030-a4bce700-3765-11eb-96c2-111f63333403.png)

Ты совсем там наглухо ебнулся?
 
Смотри, если разделять стили и логику компонентов (я сам так делаю в теллре), мб имеет смысл держать стили в одной директории с логикой, просто называть файл "styles", хотя бы, **как писали реакт еще в 2015**?

**Comment by arf1e** [comment]
Если ты сделал это по совету какого-нибудь Бычкова от мира фронтэнда, то его я тоже теперь ненавижу и считаю душным

**Comment by RuSaG0** [comment]
Реально пиздец. Короче у [лектрума ](https://lectrum.io/)видел, да и еще у каких-то [стримеров](https://www.youtube.com/user/dmitrylavr), что они разделяют стили в папке в корне, но у них все получше выглядит - они алиасами через вебпак подключали, я и сам так планировал скоро сделать. 

Для нашего случая выглядело бы примерно так:

```
resolve: {
      alias: {
          '~3/': path.resolve(__dirname, '../../../styles')
          '~4/': path.resolve(__dirname, '../../../../styles')
          '~5/': path.resolve(__dirname, '../../../../../styles')
   }
}
```
Тогда обращение было бы:

`import {C__Items__Header} from '~5/catalog/Categories/Categories'`


Да, давай стили и логику держать в одном файле, просто перед называем писать styles. Здесь доеб настолько по факту, что даже нет смысла продолжать разговор
